version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-stretch

    working_directory: ~/tokaido

    steps:
      - checkout

      - run: go mod vendor

      - run: make build-linux
      - run: sha256sum dist/tok-linux-amd64 > dist/tok-linux-amd64-sha.txt
      - run: make build-macos
      - run: sha256sum dist/tok-macos > dist/tok-macos-sha.txt
      - run: make build-windows
      - run: sha256sum dist/tok-windows-amd64.exe > dist/tok-windows-sha.txt

      - store_artifacts:
          path: ~/tokaido/dist/
          destination: artifacts

      - persist_to_workspace:
          root: ~/tokaido/
          paths:
            - dist

  release:
    docker:
      - image: circleci/golang:1.13-stretch
    steps:
      - attach_workspace:
          at: ./
      - run: go get github.com/tcnksm/ghr
      - run: echo tag = ${CIRCLE_TAG}
      - run:
          name: "Publish Linux Release on GitHub"
          command: ghr -t ${GITHUB_TOKEN} -u ironstar-io -r tokaido -b "Please record your change log here" -c ${CIRCLE_SHA1} -draft -prerelease -delete ${CIRCLE_TAG} ./dist/

workflows:
  version: 2
  build:
    jobs:
      - build

  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
